package com.kk.generator.mapper;

import com.kk.generator.entity.Personlevel;
import com.kk.generator.entity.PersonlevelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PersonlevelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personlevel
     *
     * @mbg.generated
     */
    long countByExample(PersonlevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personlevel
     *
     * @mbg.generated
     */
    int deleteByExample(PersonlevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personlevel
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personlevel
     *
     * @mbg.generated
     */
    int insert(Personlevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personlevel
     *
     * @mbg.generated
     */
    int insertSelective(Personlevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personlevel
     *
     * @mbg.generated
     */
    List<Personlevel> selectByExample(PersonlevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personlevel
     *
     * @mbg.generated
     */
    Personlevel selectByPrimaryKey(Integer lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personlevel
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Personlevel record, @Param("example") PersonlevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personlevel
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Personlevel record, @Param("example") PersonlevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personlevel
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Personlevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personlevel
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Personlevel record);
}