package com.kk.generator.mapper;

import com.kk.generator.entity.Personcard;
import com.kk.generator.entity.PersoncardExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PersoncardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personcard
     *
     * @mbg.generated
     */
    long countByExample(PersoncardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personcard
     *
     * @mbg.generated
     */
    int deleteByExample(PersoncardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personcard
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personcard
     *
     * @mbg.generated
     */
    int insert(Personcard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personcard
     *
     * @mbg.generated
     */
    int insertSelective(Personcard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personcard
     *
     * @mbg.generated
     */
    List<Personcard> selectByExample(PersoncardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personcard
     *
     * @mbg.generated
     */
    Personcard selectByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personcard
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Personcard record, @Param("example") PersoncardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personcard
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Personcard record, @Param("example") PersoncardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personcard
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Personcard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personcard
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Personcard record);
}