package com.kk.generator.entity;

public class Personlevel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personlevel.lid
     *
     * @mbg.generated
     */
    private Integer lid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personlevel.lname
     *
     * @mbg.generated
     */
    private String lname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personlevel.lid
     *
     * @return the value of personlevel.lid
     *
     * @mbg.generated
     */
    public Integer getLid() {
        return lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personlevel.lid
     *
     * @param lid the value for personlevel.lid
     *
     * @mbg.generated
     */
    public void setLid(Integer lid) {
        this.lid = lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personlevel.lname
     *
     * @return the value of personlevel.lname
     *
     * @mbg.generated
     */
    public String getLname() {
        return lname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personlevel.lname
     *
     * @param lname the value for personlevel.lname
     *
     * @mbg.generated
     */
    public void setLname(String lname) {
        this.lname = lname == null ? null : lname.trim();
    }
}